package org.example;


/**
 * Maps ResultSet rows into Autore objects.
 *
 * The skeleton for this class was autogenerated by Torque on:
 *
 * [Thu May 15 23:42:39 CEST 2025]
 *
 */
public class AutoreRecordMapper extends BaseAutoreRecordMapper
{
    /** Serial version */
    private static final long serialVersionUID = 1747345359562L;



}
