package org.example;


/**
 * The skeleton for this class was autogenerated by Torque on:
 *
 * [Thu May 15 23:42:38 CEST 2025]
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 */

public  class Genere
    extends org.example.BaseGenere
{
    /** Serial version */
    private static final long serialVersionUID = 1747345358454L;



}
