package org.example;

/**
 * The skeleton for this class was autogenerated by Torque on:
 *
 * [Thu May 15 23:42:39 CEST 2025]
 *
 * This class provides static wrappers for the peer implementation classes.
 * This class will only be generated as long as it does not already exist
 * in the output directory.
 */

public class LibroPeer
    extends org.example.BaseLibroPeer
{

}
