package org.example;


/**
 * Maps ResultSet rows into Libro objects.
 *
 * The skeleton for this class was autogenerated by Torque on:
 *
 * [Thu May 15 23:42:39 CEST 2025]
 *
 */
public class LibroRecordMapper extends BaseLibroRecordMapper
{
    /** Serial version */
    private static final long serialVersionUID = 1747345359567L;



}
